CREATE TABLE Movies (
    movie_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR2(255) NOT NULL,
    release_year NUMBER NOT NULL,
    genre VARCHAR2(100),
    duration NUMBER -- duration in minutes
);

CREATE TABLE Actors (
    actor_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(255) NOT NULL,
    dob DATE
);
CREATE TABLE Movie_Actors (
    movie_id NUMBER,
    actor_id NUMBER,
    PRIMARY KEY (movie_id, actor_id),
    FOREIGN KEY (movie_id) REFERENCES Movies(movie_id),
    FOREIGN KEY (actor_id) REFERENCES Actors(actor_id)
);
CREATE TABLE Showtimes (
    showtime_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    movie_id NUMBER,
    show_date DATE,
    show_time TIMESTAMP,
    FOREIGN KEY (movie_id) REFERENCES Movies(movie_id)
);
CREATE TABLE Movies (
    movie_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR2(255) NOT NULL,
    release_year NUMBER NOT NULL,
    genre VARCHAR2(100),
    duration NUMBER -- duration in minutes
);

CREATE TABLE Actors (
    actor_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(255) NOT NULL,
    dob DATE
);

CREATE TABLE Movie_Actors (
    movie_id NUMBER,
    actor_id NUMBER,
    PRIMARY KEY (movie_id, actor_id),
    FOREIGN KEY (movie_id) REFERENCES Movies(movie_id),
    FOREIGN KEY (actor_id) REFERENCES Actors(actor_id)
);

CREATE TABLE Showtimes (
    showtime_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    movie_id NUMBER,
    show_date DATE,
    show_time TIMESTAMP,
    FOREIGN KEY (movie_id) REFERENCES Movies(movie_id)
);

CREATE TABLE Tickets (
    ticket_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    showtime_id NUMBER,
    seat_number VARCHAR2(10),
    price NUMBER(5, 2),
    FOREIGN KEY (showtime_id) REFERENCES Showtimes(showtime_id)
);
==========================================================================================================================================
- Insert Movies
INSERT INTO Movies (title, release_year, genre, duration) VALUES ('Inception', 2010, 'Sci-Fi', 148);
INSERT INTO Movies (title, release_year, genre, duration) VALUES ('The Dark Knight', 2008, 'Action', 152);
INSERT INTO Movies (title, release_year, genre, duration) VALUES ('Interstellar', 2014, 'Sci-Fi', 169);
-- Insert Actors using separate INSERT statements
INSERT INTO Actors (name, dob) VALUES ('Leonardo DiCaprio', TO_DATE('1974-11-11', 'YYYY-MM-DD'));
INSERT INTO Actors (name, dob) VALUES ('Christian Bale', TO_DATE('1974-01-30', 'YYYY-MM-DD'));
INSERT INTO Actors (name, dob) VALUES ('Matthew McConaughey', TO_DATE('1969-11-04', 'YYYY-MM-DD'));
-- Insert Movie_Actors using separate INSERT statements
INSERT INTO Movie_Actors (movie_id, actor_id) VALUES (1, 1); -- Inception, Leonardo DiCaprio
INSERT INTO Movie_Actors (movie_id, actor_id) VALUES (2, 2); -- The Dark Knight, Christian Bale
INSERT INTO Movie_Actors (movie_id, actor_id) VALUES (3, 1); -- Interstellar, Leonardo DiCaprio
INSERT INTO Movie_Actors (movie_id, actor_id) VALUES (3, 3); 
-- Interstellar, Matthew McConaughey
-- Insert Showtimes using separate INSERT statements
INSERT INTO Showtimes (movie_id, show_date, show_time) VALUES (1, TO_DATE('2024-10-05', 'YYYY-MM-DD'), TO_TIMESTAMP('18:00:00', 'HH24:MI:SS'));
INSERT INTO Showtimes (movie_id, show_date, show_time) VALUES (2, TO_DATE('2024-10-05', 'YYYY-MM-DD'), TO_TIMESTAMP('20:30:00', 'HH24:MI:SS'));
INSERT INTO Showtimes (movie_id, show_date, show_time) VALUES (3, TO_DATE('2024-10-06', 'YYYY-MM-DD'), TO_TIMESTAMP('19:00:00', 'HH24:MI:SS'));

-- Insert Tickets using separate INSERT statements
INSERT INTO Tickets (showtime_id, seat_number, price) VALUES (1, 'A1', 10.00);
INSERT INTO Tickets (showtime_id, seat_number, price) VALUES (1, 'A2', 10.00);
INSERT INTO Tickets (showtime_id, seat_number, price) VALUES (2, 'B1', 12.00);
INSERT INTO Tickets (showtime_id, seat_number, price) VALUES (3, 'C1', 8.50);
==========================================================================================================================================================
-- Update ticket price for a specific seat
UPDATE Tickets SET price = 11.00 WHERE seat_number = 'A1';
====================================================================================================================================================
-- Delete a specific ticket
DELETE FROM Tickets WHERE ticket_id = 4;
-- Assuming ticket_id 4 corresponds to B1

=======================================================================================================================================================

-- Get all movies with their actors
SELECT m.title, a.name 
FROM Movies m
JOIN Movie_Actors ma ON m.movie_id = ma.movie_id
JOIN Actors a ON ma.actor_id = a.actor_id;

-- Get showtimes with movie titles
SELECT s.showtime_id, m.title, s.show_date, s.show_time 
FROM Showtimes s
JOIN Movies m ON s.movie_id = m.movie_id;

======================================================================================================================================================

-- Get all tickets for a specific movie
SELECT * 
FROM Tickets 
WHERE showtime_id IN (SELECT showtime_id FROM Showtimes WHERE movie_id = 1); -- For "Inception"

